version: '3.8'

services:
  mysql:
    build:
      context: ./app_dockerfiles/ubuntu18.04_mysql_server
      dockerfile: Dockerfile
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - ./app_data/mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mlflow
      MYSQL_USER: mlflow_user
      MYSQL_PASSWORD: mlflow
    restart: always

  mlflow:
    build:
      context: ./app_dockerfiles/ubuntu22.04_mlflow_server
      dockerfile: Dockerfile
    container_name: mlflow_container
    ports:
      - "5000:5000"
    expose: 
      - "5000"
    depends_on:
      - mysql
    volumes:
      - ./app_data/mlflow_tracked_data/mlruns:/mlruns
    environment:
      BACKEND_STORE_URI: mysql+pymysql://mlflow_user:mlflow@mysql:3306/db_mlflow
      ARTIFACT_STORE_URI: /mlruns

  model:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: model_container
    volumes:
      - ./app_data:/app/app_data
    depends_on:
      - mlflow